Sprite renderer support
shamsdev/davinci pull request #13
Opened 2020-11-21 04:56 UTC by indikman

Added a new RendererType
Added a new method (into) that requests a SpriteRenderer as a parameter
Added the default placeholder loading for the spriterender
Added the spite case for the ImageLoader Ienumerator

Example scene for sprite loader is added

2021-01-19 12:27 UTC, Techie-Pi approved these changes

2021-08-07 13:35 UTC, shamsdev requested changes
Thank you @indikman, You commits contains lots of unnecessary file changes on main script. Code refactoring is not acceptable. Please review your changes and make it more clear. 
Regards.

2021-08-10 17:13 UTC, Techie-Pi commented
Because of this PR being almost 10 months old, I'm going to do the same as did with #25 (old #20).
That new PR is going to replace this one, I'll edit this comment when I create it

2021-08-12 12:48 UTC, shamsdev commented
Thank you very much @indikman #26 has been merged.

2021-08-12 12:48 UTC, closed without merging