Replacing Obsolete WWW with UnityWebRequest
shamsdev/davinci pull request #20
Opened 2021-08-04 13:40 UTC by khmaies5

Unity is going to replace WWW with UnityWebRequest, they are advising users to use UnityWebRequest in the docs
Obsolete: WWW has been replaced with UnityWebRequest.

2021-08-05 20:12 UTC, Techie-Pi approved these changes
looks good

2021-08-05 20:32 UTC, khmaies5 commented
Www is supported until unity 2017 starting from 2018 and up you need to use UnityWebRequest.
-this merge will break this asset in unity 2017 and older.
You can say in docs that this asset requires Unity 2018 and up or i can add a condition in the code to check the version of Unity and use the proper API depending on that

2021-08-05 20:36 UTC, Techie-Pi commented
We could create an option to use WWW instead on UnityWebRequest, something like ``.legacyWww(true)``

2021-08-06 11:00 UTC, khmaies5 commented
i can update the code like this 
``` 
#if UNITY_2018_3_OR_NEWER
    private UnityWebRequest www;
#else
    private WWW www;
#endif

2021-08-06 11:11 UTC, Techie-Pi commented
That's a better option, great

2021-08-06 11:49 UTC, Techie-Pi commented
Great! There's nothing left, right?

2021-08-06 11:52 UTC, khmaies5 commented
yep, that's all

2021-08-06 11:58 UTC, Techie-Pi approved these changes

2021-08-07 13:43 UTC, shamsdev requested changes
Hello @khmaies5, Thank you for your great work. Your commit contains unnecessary changes and auto-code refactoring. this is not acceptable. please only commit your actual changes. that will be more clearer.
Again thank you for your contribution. 
Regards.

2021-08-07 14:30 UTC, khmaies5 commented
@shamsdev I only changed the lines that needed to be changed, the other changes for some reason are automatically detected by git despite I didn't touch them, maybe its file encoding thing since I use windows vs code.

2021-08-08 11:15 UTC, Techie-Pi commented
Same for #13

2021-08-09 14:11 UTC, khmaies5 commented
@Techie-Pi i must pull the new changes in the main repo and push again ?

2021-08-09 15:10 UTC, Techie-Pi commented
The simpler option is to fetch upstream when #23 is merged and use something like ``eclint`` to fix your local file, that could end with one of the following possibilities:
- the unnecesary changes are canceled by upstream and only the relevant ones are left
- in this PR everything stays similar to right now with the unnecesary changes, in that case, maybe an exception could be made, and the pull request is merged

2021-08-09 15:14 UTC, Techie-Pi commented
An alternative could be to close this PR and add the changes again when #23 is merged, without the unnecesary changes already commited

2021-08-10 12:13 UTC, Techie-Pi commented
@khmaies5 I'm going to create soon a PR on your fork fixing the problems, stay tuned

2021-08-10 13:37 UTC, khmaies5 commented
I will close this pull request and wait for your changes and then re submit my changes

2021-08-10 13:37 UTC, closed without merging

2021-08-10 13:56 UTC, Techie-Pi commented
Great, I'll ask you to remove the ``Update-to-UnityWebRequest`` branch on [khmaies5/davinci](https://github.com/khmaies5/davinci) and create it again.
I'll create a PR with the code changes once the new branch is created on your side

2021-08-10 14:14 UTC, Techie-Pi commented
I saw you deleted the branch, now you could fetch upstream and I'll take care of everything else. Thank you so much and sorry for all the inconveniences 😅

2021-08-10 14:40 UTC, khmaies5 commented
@Techie-Pi Not problem dude there is not inconvenience, this is a great asset and its great that is not abandoned.
I created a new pull request #25

2021-08-10 14:42 UTC, Techie-Pi commented
Thank you so much!! Really, thank you 😉